### ISSUE TITLE
Fast 180 rotation makes camera view be upside down.

### ISSUE THREAD

**Issue by aleksas** [googlesamples/android-Camera2Basic#103] opened 2018-02-20 16:29 UTC
Devices tested on: **Nexus 5**, **LG -D855**

**To reproduce**:
1. Run the app.
2. Position device horizontaly (see screenshot **A**).
3. Rotate quickly 180 deg. so that the device is in horizontal position but upside-down compared to 2.
4. The result is upside down camera view (see screenshot **B**).

**Probable cause**:
It seams that View is not destroyed/recreated; corresponding life-cycle callbacks like onSurfaceChanged are not called, consequently preview transformation is not recalculated.

**Suggested solution**:
Force preview transformation recalculation on [OrientationEventListener.onOrientationChanged](https://developer.android.com/reference/android/view/OrientationEventListener.html) call (with, for instance, [SensorManager.SENSOR_DELAY_UI](https://developer.android.com/reference/android/hardware/SensorManager.html#SENSOR_DELAY_UI) setting). At least that's what I do when handling opengl drawing.

Screenshot **A**:
![screenshot_20180220-180614](https://user-images.githubusercontent.com/594470/36435038-3098b018-1669-11e8-9eb8-f82ef6050785.png)

Screenshot **B**:
![screenshot_20180220-180629](https://user-images.githubusercontent.com/594470/36435036-2f02d116-1669-11e8-833d-7d0051797eb5.png)

Proper screen rotation animation:
![20180221_171828](https://user-images.githubusercontent.com/594470/36488273-b03c8278-172b-11e8-9e6b-34c1322b12f6.gif)

Faulty screen rotation animation:
![20180221_171930](https://user-images.githubusercontent.com/594470/36488325-d014c79a-172b-11e8-97e2-4f69c14716f1.gif)

**Comment by schildbach** [comment] 2018-02-20 18:11
Duplicate of #43

**Comment by codingjeremy** [comment] 2019-09-19 22:52
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed by codingjeremy** 2019-09-19 22:52 UTC
