### ISSUE TITLE
Image isnt captured with front camera

### ISSUE THREAD

**Issue by shailesh17mar** [googlesamples/android-Camera2Basic#30] opened 2016-01-14 20:58 UTC

**Comment by jibinjoseph** [comment] 2016-02-19 06:02
I am facing same problem , i have solved the issue by replacing  this code in lockFocus () -- mCaptureSession.capture(mPreviewRequestBuilder.build(),mCaptureCallback,
                            mBackgroundHandler);    instead this  you should call  captureStillPicture(); ,,But this is not a proper solution for this bug ,If you found any other solution please comment it here..

**Comment by Moeybanana** [comment] 2016-02-23 09:35
UNSUBSCRIBE

On Fri, Feb 19, 2016 at 8:02 AM, jibinjoseph <notifications@github.com>
wrote:

> I am facing same problem , i have solved the issue by replacing this code
> in lockFocus () --
> mCaptureSession.capture(mPreviewRequestBuilder.build(),mCaptureCallback,
> mBackgroundHandler); instead this you should call captureStillPicture();
> ,,But this is not a proper solution for this bug ,If you found any other
> solution please comment it here..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/android-Camera2Basic/issues/30#issuecomment-186074995>
> .
>



-- 
Mohsen Mouralli
+1-971-55-6115950

**Comment by RoundSparrow** [comment] 2016-05-25 16:32
My guess is that the problem is that the front camera does not have Auto-focus and the Rear camera does.  There is a bug related to devices not having auto-focus.  See issue #33 for code to work around that problem and see if it resolves this one.

**Comment by LiHanGuang** [comment] 2017-08-09 09:55
hope it help you.

> copy from : https://stackoverflow.com/questions/33127258/front-camera-in-camera2-not-capturing-image

The problem is that many front-facing cameras have a fixed focus distance. So after the autofocus trigger in lockFocus() the autofocus state (CONTROL_AF_STATE) remains INACTIVE and the autofocus trigger does nothing.

So in order to make it work you need to check whether autofocus is supported or not. To do so, add the following to setUpCameraOutputs():

int[] afAvailableModes = characteristics.get(CameraCharacteristics.CONTROL_AF_AVAILABLE_MODES);

if (afAvailableModes.length == 0 || (afAvailableModes.length == 1
        && afAvailableModes[0] == CameraMetadata.CONTROL_AF_MODE_OFF)) {
    mAutoFocusSupported = false;
} else {
    mAutoFocusSupported = true;
}
Finally don't lock focus if its not supported when you want to take a picture:

private void takePicture() {
    if (mAutoFocusSupported) {
        lockFocus();
    } else {
        captureStillPicture();
    }
}

**Comment by codingjeremy** [comment] 2019-09-19 22:59
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed by codingjeremy** 2019-09-19 22:59 UTC
