### ISSUE TITLE
Android Nougat 

### ISSUE THREAD

**Issue by brunozaranza** [googlesamples/android-Camera2Basic#82] opened 2017-06-01 12:46 UTC
How should be the behavior in the API 24? Inside my cell phone (Moto G4 plus) didn't take a picture, button didn't works.

**Comment by lucavallerini** [comment] 2017-06-01 18:03
@brunozaranza If it's the same problem on the Moto G5+ then it is caused by the fact that the device has a passive Auto focus: when you press the button it actual tries to shoot a photo but the procedure stop because of an unexpected state of the variable afState.

_Sent from my Motorola Moto G (5) Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by anakateesu** [comment] 2017-06-29 01:19
The app freezes at the line mCameraOpenCloseLock.acquire(); for Android 7.
Any fixes?

**Comment by codingjeremy** [comment] 2019-09-19 22:53
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed by codingjeremy** 2019-09-19 22:53 UTC
